# General settings
set -g default-terminal 'tmux-256color' # set default terminal type
set -as terminal-features ',xterm-256color:RGB' # enable true color
set -g mouse on # enable mouse
set -g history-limit 10000 # enlarge history entry limit
set -sg escape-time 0 # for faster response

# Prefix key
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Window
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -g base-index 1

# Pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

setw -g pane-base-index 1

# Navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload configuration with ease
bind r source-file ~/.config/tmux/tmux.conf \; display 'Config reloaded!'

# Vi style copying
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# Customization
set -g status-style 'bg=terminal,fg=terminal'
set -g status-justify left

set -g status-left-length 30
set -g status-left '#[fg=color4,bold] ◈ #S #[default]#[fg=color7]│ '

set-window-option -g window-status-style 'fg=color7,dim'
set-window-option -g window-status-format ' #I:#W '

set-window-option -g window-status-current-style 'fg=color4,bold,reverse'
set-window-option -g window-status-current-format ' #I:#W '

set -g status-right-length 60
set -g status-right '#[fg=color3,bold]#{?client_prefix, [^A] ,}#[fg=color7]│ #[fg=color7]%H:%M │ %Y-%m-%d '

set -g pane-border-style 'fg=color8'
set -g pane-active-border-style 'fg=color4'

# List of plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'jaclu/tmux-menus'

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
