[tools]
"aqua:Schniz/fnm" = "latest"
deno = "latest"
zoxide = "latest"
bun = "latest"
uv = "latest"
eza = "latest"
opam = { version = "latest", asset_pattern = "opam-*-{gnu_arch}-{os}" }
codex = "latest"
claude-code = "latest"
opencode = "latest"
shfmt = "latest"
dprint = "latest"
"github:sass/dart-sass" = "latest"
dart = { version = "latest", url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-x64-release.zip", version_expr = 'fromJSON(body).prefixes | filter({ # matches "^channels/stable/release/(\\d+\\.\\d+\\.\\d+)/$" }) | map({split(#, "/")[3]}) | sortVersions()', version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/" }
usage = "latest"
neovim = "latest"
gh = "latest"
ripgrep = "latest"
jq = "latest"
miller = "latest"
fd = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
go = "latest"
btop = "latest"
dua = "latest"
bottom = "latest"
dust = "latest"
lazygit = "latest"
gdu = "latest"
fzf = "latest"
"github:llvm/llvm-project" = "latest"
